# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import windowsystem_pb2 as windowsystem__pb2


class WindowOcServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.windowsOC = channel.unary_unary(
                '/WindowOcService/windowsOC',
                request_serializer=windowsystem__pb2.WindowRequest.SerializeToString,
                response_deserializer=windowsystem__pb2.WindowReply.FromString,
                )


class WindowOcServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def windowsOC(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_WindowOcServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'windowsOC': grpc.unary_unary_rpc_method_handler(
                    servicer.windowsOC,
                    request_deserializer=windowsystem__pb2.WindowRequest.FromString,
                    response_serializer=windowsystem__pb2.WindowReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'WindowOcService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class WindowOcService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def windowsOC(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/WindowOcService/windowsOC',
            windowsystem__pb2.WindowRequest.SerializeToString,
            windowsystem__pb2.WindowReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
