// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppSystem.proto

package ds.examples.appsystem;

public interface HeatReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:appsystem.HeatReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   */
  java.lang.String getMessage();
  /**
   * <code>string message = 1;</code>
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
