// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: AppSystem.proto

package ds.examples.appsystem;

public interface HeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:appsystem.HeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temp = 1;</code>
   */
  int getTemp();

  /**
   * <code>int32 number = 2;</code>
   */
  int getNumber();
}
