// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatSystem.proto

package ds.examples.heatsystem;

public interface HeatRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heatsystem.HeatRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 temp = 1;</code>
   */
  int getTemp();

  /**
   * <code>int32 number = 2;</code>
   */
  int getNumber();
}
