// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatSystem.proto

package ds.examples.heatsystem;

public final class HeatSystemServiceImp {
  private HeatSystemServiceImp() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heatsystem_HeatRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heatsystem_HeatRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_heatsystem_HeatReply_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_heatsystem_HeatReply_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020HeatSystem.proto\022\nheatsystem\"+\n\013HeatRe" +
      "quest\022\014\n\004temp\030\001 \001(\005\022\016\n\006number\030\002 \001(\005\"\034\n\tH" +
      "eatReply\022\017\n\007message\030\001 \001(\t2S\n\023HeatSystemG" +
      "reetings\022<\n\010sayHello\022\027.heatsystem.HeatRe" +
      "quest\032\025.heatsystem.HeatReply\"\000B0\n\026ds.exa" +
      "mples.heatsystemB\024HeatSystemServiceImpP\001" +
      "b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_heatsystem_HeatRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_heatsystem_HeatRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heatsystem_HeatRequest_descriptor,
        new java.lang.String[] { "Temp", "Number", });
    internal_static_heatsystem_HeatReply_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_heatsystem_HeatReply_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_heatsystem_HeatReply_descriptor,
        new java.lang.String[] { "Message", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
