// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: HeatSystem.proto

package ds.examples.heatsystem;

public interface WindowReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:heatsystem.WindowReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 val = 1;</code>
   */
  int getVal();
}
